language: java

cache:
  directories:
    - '$HOME/.m2/repository'

jobs:
  include:
  - os: linux
    dist: xenial
    jdk: openjdk8
  - os: linux
    dist: xenial
    jdk: openjdk11
  - os: linux
    dist: bionic
    jdk: openjdk8
  - os: linux
    dist: bionic
    jdk: openjdk11
  - os: linux
    dist: bionic
    jdk: oraclejdk11
  - os: linux
    dist: bionic
    jdk: oraclejdk13
  - os: linux
    dist: trusty
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode11
  - os: osx
    osx_image: xcode11.3

script:
  - mvn -B -P jacoco clean compile test install
