# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: master
    paths-ignore:
    - '**.gitattributes'
    - '**.gitignore'
    - LICENSE
    - NOTICE
    - '**.md'
  pull_request:
    branches: master
    paths-ignore:
    - '**.gitattributes'
    - '**.gitignore'
    - LICENSE
    - NOTICE
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        jdk: [8, 9, 10, 11, 12]
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK  ${{ matrix.jdk }}
      uses: actions/setup-java@master
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Maven
      run: mvn -P jacoco -B clean package --file pom.xml
