# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: master
    paths-ignore:
    - '**.gitattributes'
    - '**.gitignore'
    - '**.md'
  pull_request:
    branches: master
    paths-ignore:
    - '**.gitattributes'
    - '**.gitignore'
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        jdk: [8, 9, 10, 11, 12]
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK  ${{ matrix.jdk }}
      uses: actions/setup-java@master
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Maven
      run: mvn -P jacoco -B clean package --file pom.xml

  snyk:
    if: ${{ secrets.SNYK_TOKEN != '' && needs.build.result = 'success' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonarcloud:
    if: ${{ secrets.SONAR_TOKEN != '' && needs.build.result = 'success' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@master
      with:
        java-version: 11
        server-id: sonar
        server-sonar.login: ${{ secrets.SONAR_TOKEN }}
    - name: SonarCloud Scan
      run: mvn -P jacoco -B -Dsonar.projectKey=jsonurl_jsonurl-java -Dsonar.organization=jsonurl -Dsonar.host.url=https://sonarcloud.io package sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
