# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    paths-ignore:
    - '**.gitattributes'
    - '**.gitignore'
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.gitattributes'
    - '**.gitignore'
    - '**.md'

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 8
      uses: actions/setup-java@master
      with:
        java-version: 8
    - name: Set artifact version
      run: script/version_snapshot.sh
      shell: bash
    - name: Stage artifacts
      run: mvn -B -DaltDeploymentRepository=ossrh::default::file:snapshot/ deploy
    - name: Package artifacts
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: jsonurl-maven-repository
        path: snapshot/*

  matrix-build:
    needs: artifact
    if: needs.artifact.result == 'success'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        jdk: [8, 9, 10, 11, 12]
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK  ${{ matrix.jdk }}
      uses: actions/setup-java@master
      with:
        java-version: ${{ matrix.jdk }}
    - name: Cache Maven dependencies
      timeout-minutes: 10
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set artifact version
      run: script/version_snapshot.sh
      shell: bash
    - name: Build with Maven
      run: mvn -P jacoco -B clean package verify --file pom.xml

  snyk:
    needs: artifact
    if: |
        github.event_name == 'push'
            && endsWith( github.ref, '/master' )
            && needs.artifact.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonarcloud:
    needs: artifact
    if: |
        github.event_name == 'push'
            && endsWith( github.ref, '/master' )
            && needs.artifact.result == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git fetch --unshallow
    - name: Set up JDK 11
      uses: actions/setup-java@master
      with:
        java-version: 11
    - name: Set artifact version
      run: script/version_snapshot.sh
      shell: bash
    - name: SonarCloud Scan
      run: mvn -P jacoco -B -Dsonar.projectKey=jsonurl_jsonurl-java -Dsonar.organization=jsonurl -Dsonar.host.url=https://sonarcloud.io package sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

